name:                leek-wars-generator-haskell-server
version:             0.1.0.0
github:              "Shakadak/leek-wars-generator-haskell-server"
license:             MIT
author:              "Nathanaël Pineau"
maintainer:          "nathanael.pineau@gmail.com"
copyright:           "2018 Nathanaël Pineau"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Shakadak/leek-wars-generator-haskell-server#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- aeson
- aeson-compat
- attoparsec
- base-compat
- blaze-html
- blaze-markup
- bytestring
- directory
- http-media
- lucid
- mtl
- string-conversions
- time
- wai
- warp

library:
  source-dirs: src

executables:
  lwghs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leek-wars-generator-haskell-server

tests:
  lwghs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leek-wars-generator-haskell-server
